name: Security Pipeline

on: [push, pull_request]

jobs:
  security_pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: Install Bandit
        run: |
          pip install bandit
          
      - name: Run Static Code Analysis (SAST) with Bandit
        run: |
          bandit -r . -f json -o bandit-report.json

  security_check:  # Ensure proper indentation
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Use the same version for consistency

      - name: Run Security Scan
        run: echo "Running Security Scan..."

